#!/bin/sh
#
# newrhelic Start up the NewRHELic Plugin for New Relic Monitoring
#
# chkconfig:   35 99 10
# description: A RHEL/CentOS-centric monitoring plugin for New Relic \
# processname: newrhelic
# config: /etc/newrhelic.conf
# pidfile: /var/run/newrhelic.pid
# logfile: /var/log/newrhelic.log

# Source function library.
. /etc/rc.d/init.d/functions

exec="/usr/bin/newrhelic"
prog="newrhelic"
config="/etc/newrhelic.conf"

[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog

lockfile=/var/lock/subsys/$prog

go_start(){
    echo  -n $"Starting $prog:"
    /usr/bin/newrhelic start && success || failure
    echo
}

go_stop(){
    echo -n $"Stopping $prog:"
    /usr/bin/newrhelic stop && success || failure
    echo
}

start() {
    rh_status 2>&1 > /dev/null
    [ $? -ne 0 ] && go_start || echo "$prog is already running!"
}

stop() {
    rh_status 2>&1 > /dev/null
    [ $? -ne 3 ] && go_stop || echo "$prog is already stopped!"
}

restart() {
    stop
    start
}

rh_status() {
    # run checks to determine if the service is running or use generic status
    status $prog
}

case $1 in
    start )
        start
        ;;
    stop )
        stop
        ;;
    restart )
        restart
        ;;
    status )
        rh_status
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac
exit $?
